apiVersion: apps/v1
kind: Deployment #Menentukan jenis = Deployment
metadata:
  name: shipping-deployment #Memberi nama deployment
spec:
  replicas: 1 #Menentukan jumlah replica

  selector: #Menentukan target deployment untuk setiap label yang ditentukan dibawah
    matchLabels:
      app: shipping

  template: #Menentukan konfigurasi template pod
    metadata:
      labels:
        app: shipping

    spec:
      containers: #Menentukan konfigurasi container shipping-service
      - name: shipping-service
        image: ghcr.io/dha-lang/shipping-service:latest
        ports: #Menentukan port
          - containerPort: 3001
        env: #Menambahkan variabel env
          - name: PORT
            value: "3001"
          - name: AMQP_URL
            value: "amqp://pengguna:pengguna@10.107.147.91:5672"