apiVersion: apps/v1
kind: Deployment #Menentukan jenis = Deployment
metadata:
  name: order-deployment #Memberi nama deployment
spec:
  replicas: 1 #Menentukan jumlah replica

  selector: #Menentukan target deployment untuk setiap label yang ditentukan dibawah
    matchLabels:
      app: order

  template: #Menentukan konfigurasi template pod
    metadata:
      labels:
        app: order

    spec:
      containers: #Menentukan konfigurasi container order-service
      - name: order-service
        image: ghcr.io/dha-lang/order-service:latest
        ports: #Menentukan port
          - containerPort: 3000
        env: #Menambahkan variabel env
          - name: PORT
            value: "3000"
          - name: AMQP_URL
            value: "amqp://pengguna:pengguna@10.107.147.91:5672"