apiVersion: v1
kind: Service #Menentukan jenis = service
metadata:
  name: order-svc #Memberi nama untuk service

spec:
  selector: #Menentukan target service untuk setiap label yang ditentukan dibawah
    app: order

  ports: #Menentukan port, target port, dan protokol
  - protocol: TCP
    port: 3000
    targetPort: 3000